services:
  ollama:
    build: ollama
    ports:
      - "11434:11434"
    networks:
      - llama
    entrypoint: ['/bin/bash', '/pull-llama3.sh']

  fastapi:
    build:
      context: .
      dockerfile: fastapi/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - fastapi

  db:
    build: database
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

networks:
  llama:
    driver: bridge
  fastapi:
    driver: bridge