[tool.poetry]
name = "employee-review"
version = "0.1.0"
description = ""
authors = ["Michaela <miselka12345@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
torch = "^2.5.1"
transformers = "^4.46.2"
huggingface = "^0.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
